title: Redouane Bouazza # your name (or website title) here
logo: "/images/Photo_cv-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mathematical and Data science Engineering student seeking an opportunity in the field of machine learning and optimisation with the objective to continue on a thesis.
  Detail-Oriented and curious, my prior internships in machine learning guided me to possess extensive analytical skills a great ability to work in a team.

  <a href="https://redouane-bouazza.github.io/projects">View My Projects</a>

  <a href="https://www.linkedin.com/in/redouane-bouazza-36446a165/">View My LinkedIn Profile</a>



  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
