title: Redouane Bouazza # your name (or website title) here
logo: "/images/Photo_cv-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionate about mathematics and computer science, I possess
  extensive analytical skills, a strong sense of detail and a strong
  and a great ability to work in a team.  
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/redouane-bouazza-36446a165/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
